### ISSUE TITLE
Protogen?

### ISSUE THREAD

**Issue by mholt** [tetra12/grpcweb-proxy#1]
When I run `make genfront` I am getting:

```
$ make genfront
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'protogen'
make: *** [GNUmakefile:2: genfront] Error 1
```

**Comment by tetra12** [comment]
Hi @mholt 

I updated the README. YOu need to install the Protobuf Compiler `protoc-21.4-linux` from [here](https://github.com/protocolbuffers/protobuf/releases/download/v21.4/protoc-21.4-linux-x86_64.zip) first to be able to compile protobuf for both frontend and backend

**Comment by mholt** [comment]
Thanks; I already have `protoc` installed though and in my PATH. Is there a reason I need to use that particular one?

It looks like it's looking for a file called `protogen` inside `front` or something.

**Comment by tetra12** [comment]
Which are your versions of yarn and protoc ?

`yarn -v
`protoc --version`

**Comment by mholt** [comment]
```
$ yarn --version
0.32+git

$ protoc --version
libprotoc 3.12.4
```

I followed some tutorials online to install yarn and protoc. Guess I got the wrong versions? `apt` sucks? :)

**Comment by tetra12** [comment]
Hmmmm yarn is very suspicious :thinking: Could you pls install the latest 1.x as stated in README.
Currently it's `1.22.19`. Frontend won't start with this obsolete version

**Comment by tetra12** [comment]
Yarn protogen generates TypeScript defs for protobuf. yarn dev must start a frontend. It won't work with the old version of yarn.
Tested and working for 1.22.19

**Comment by tetra12** [comment]
Install `classic-stable` for debian `1.22.19` from [here](https://classic.yarnpkg.com/lang/en/docs/install/#debian-stable)

**Comment by mholt** [comment]
K, got yarn 1.22.19 installed. Thanks!

Now I'm getting:

```
$ make genfront
yarn run v1.22.19
$ protoc --ts_out ./src/proto/greeter --proto_path ../protos ../protos/greeter.proto
protoc-gen-ts: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [GNUmakefile:2: genfront] Error 1
```

I have protoc-gen-go and protoc-gen-go-grpc but not protoc-gen-ts.

**Comment by tetra12** [comment]
Okay, now you need to do this: `cd front && yarn`. This will install all yarn deps for frontend. Then try `yarn protogen` again

**Comment by mholt** [comment]
Thanks. Now I get this error:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error vite@3.0.2: The engine "node" is incompatible with this module. Expected version "^14.18.0 || >=16.0.0". Got "12.22.9"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Another failure of apt? Installing an old version of Node? Grumble

I'm kind of thinking it'd be easier for you to implement the feature in Caddy than it will be for me to get this demo running. :P

**Comment by mholt** [comment]
Installing a newer version of Node from NodeSource, and I get:

```
$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libc-ares2 libjs-highlight.js libnode72 python3-cliapp python3-markdown python3-pygments python3-ttystatus
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 0 B/26.5 MB of archives.
After this operation, 124 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 274279 files and directories currently installed.)
Preparing to unpack .../nodejs_16.16.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (16.16.0-deb-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_16.16.0-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_16.16.0-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by tetra12** [comment]
I'm running node v18.6.0

I'm also a backend developer, who came into frontend later :smile: . Now I"m building front, back and devops stuff :sunglasses: . Frontend frameworks are really annoying to setup :angry: , compared to Go. So be patient. Because you won't build `grpcweb` test env otherwise :roll_eyes: 

I advice you to install the latest node v18.7.0. Use [this](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

**Comment by mholt** [comment]
Thank you, installing latest Node (18.6) worked. Got the demo running. Will have to tinker with it now!

**Comment by tetra12** [comment]
Great, good luck with this ! :crossed_fingers: . I may give you an access to my test server, which uses both envoy and caddy to debug things out.

The reason to setup the frontend is to allow `grpcweb` with all the browser background, like http1.1/2.0 conversion, CORS, TypeScript (client) transport, etc.

Keep in touch !
